name: CI Churrascaria

on:
  push:
    branches: [ "master" ]  # Lembre que mudamos para master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Preparar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Instalar DependÃªncias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Testar Qualidade do CÃ³digo
      run: |
        pylint --disable=C,R,W app.py

    # NOVO PASSO AQUI:
    - name: Construir Imagem Docker ğŸ³
      run: |
        docker build -t smartgrill:v1 .